Repository cilium/hubble, pull requests merged in 2020-10, with the labels that each got.

#374 cmd/peer: print tls.ServerName when available
  cmd/peer/peer.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli

#376 docs: Add link to Cilium Development Guide
  CONTRIBUTING.md
  Documentation/README.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation

#377 cmd: fix help message for the `-config` flag
  cmd/root.go
Labels: release-note/misc, ⌨️ area/cli

#378 Add reflect command
  cmd/reflect/reflect.go
  cmd/root.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.proto
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/modules.txt
Labels: release-note/minor

#381 vendor: go mod tidy && go mod vendor && go mod verify
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.proto
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
Labels: ready-to-merge, release-note/misc, 🧹 kind/cleanup

#382 actions: add go-mod check
  .github/workflows/unittests.yml
Labels: ready-to-merge, release-note/misc, 📈 kind/enhancement

#383 defaults: avoid stutter in exported names
  cmd/root.go
  cmd/status/status.go
  pkg/defaults/defaults.go
Labels: ready-to-merge, release-note/misc, 🧹 kind/cleanup

#386 Update Go to 1.15.3
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#385 cmd/config: only write provided key/value when using set subcommand
  cmd/config/set.go
Labels: ready-to-merge, release-note/misc, 🐛 kind/bug

#387 v0.6: update Go to v1.14.10
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#388 v0.5: update Go version to v1.14.10
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc

#392 vendor: bump cilium to master right before branching v1.9
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/flow/flow.pb.go
  vendor/github.com/cilium/cilium/api/v1/flow/flow.pb.json.go
  vendor/github.com/cilium/cilium/api/v1/flow/flow.proto
  vendor/github.com/cilium/cilium/api/v1/observer/observer.pb.go
  vendor/github.com/cilium/cilium/api/v1/observer/observer.proto
  vendor/github.com/cilium/cilium/pkg/hubble/api/v1/interface.go
  vendor/github.com/cilium/cilium/pkg/monitor/api/drop.go
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc

#393 set version to 0.8.0-dev
  Makefile
Labels: release-note/misc

#394 v0.7: vendor: bump cilium to v1.9.0-rc2 to track cilium v1.9 branch
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc

#396 release: fix `release` binary usage instruction
  RELEASE.md
Labels: ready-to-merge, release-note/misc

#400 readme: bump versions in releases table
  README.md
Labels: ready-to-merge, release-note/misc

#398 update CHANGELOG for releases v0.6.1 and v0.7.0
  CHANGELOG.md
Labels: ready-to-merge, release-note/misc

#397 build: ensure that binaries are always statically built
  Dockerfile
  Makefile
Labels: needs-backport/0.6, needs-backport/0.7, ready-to-merge, release-note/misc

#402 v0.7: build: ensure that binaries are always statically built
  Dockerfile
  Makefile
Labels: backport/0.7, ready-to-merge, release-note/misc, 🧰 kind/backport

#401 v0.6: backport 2020-10-20
  Dockerfile
  Makefile
Labels: backport/0.6, 🧰 kind/backport

#404 readme: update releases table, mark Hubble Relay as stable
  README.md
Labels: release-note/misc

#405 stable.txt: Bump to v0.7.0
  stable.txt
Labels: release-note/misc

#406 doc: fix broken links
  Documentation/README.md
Labels: release-note/misc, 📄 area/documentation

#399 update release instructions
  RELEASE.md
Labels: release-note/misc

#411 cmd/observe: add all flags
  cmd/observe/observe.go
  cmd/observe/observe_usage.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli, 🌟 kind/feature
