Repository cilium/hubble, pull requests merged in 2020-06, with the labels that each got.

#278 update Go version to v1.14.4 and alpine base image to v3.12
  .github/workflows/unittests.yml
  Dockerfile
Labels: 📈 kind/enhancement

#279 update Go version to v1.14.4 and alpine base image to v3.12
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc

#280 update Go version to v1.14.4 and alpine base image to v3.12
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc

#283 Require Cilium 1.7.x
  Documentation/installation.md
Labels: 📄 area/documentation

#293 Remove version from release artifact file names
  Makefile
Labels: release-note/misc

#294 Remove version from release artifact file names
  Makefile
Labels: release-note/misc

#310 backport: Re-add images linked in README
  Documentation/images/dns.png
  Documentation/images/http.png
  Documentation/images/hubble_arch.png
  Documentation/images/hubble_logo.png
  Documentation/images/network_and_tcp.png
  Documentation/images/network_policy_pod.png
  Documentation/images/servicemap.png
Labels: 🧰 kind/backport
