Repository cilium/hubble, pull requests merged in 2020-09, with the labels that each got.

#360 Fixes SC2038 in check-fmt.sh
  contrib/scripts/check-fmt.sh
Labels: release-note/misc

#358 printer: ommit node name from output
  cmd/observe/observe.go
  pkg/printer/options.go
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli, 🌟 kind/feature

#365 update Go version to v1.15.2
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#366 v0.6: update Go version to v1.14.9
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#367 v0.5: update Go version to v1.14.9
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc
