Repository cilium/hubble, pull requests merged in 2020-07, with the labels that each got.

#316 cmd: add support for fish and powershell completion
  cmd/completion.go
Labels: release-note/minor, ⌨️ area/cli, 🌟 kind/feature

#317 .gitattributes: hide go.sum and vendor/modules.txt in pull requests
  .gitattributes
Labels: area/misc, release-note/misc

#318 observe: Document default flow count output
  cmd/observe/observe.go
  pkg/defaults/defaults.go
Labels: release-note/misc, ⌨️ area/cli

#319 update Go version to v1.14.5
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: area/misc, needs-backport/0.5, needs-backport/0.6

#321 make: fix release build directory ownership
  Makefile
Labels: area/misc, needs-backport/0.6, release-note/misc, 🧹 kind/cleanup

#327 README: fix broken link to metrics documentation
  README.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation

#330 cmd/status: Add flows per second to `hubble status`
  cmd/status/status.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli

#322 Readme: remove old beta warning and make a components table
  README.md
Labels: release-note/misc

#332 helm: Bump image to v0.5.2
  install/kubernetes/hubble/values.yaml
Labels: release-note/misc
