Repository cilium/hubble, pull requests merged in 2020-04, with the labels that each got.

#210 cmd/observe: use flags.DurationVar instead of StringVar for timeout flag
  cmd/observe/observe.go
Labels: ⌨️ area/cli, 🧹 kind/cleanup

#216 server: Introduce per-request context
  pkg/server/local_observer.go
Labels: 🐛 kind/bug

#224 defaults: Introduce new defaults for embedded Hubble
  cmd/observe/observe.go
  cmd/status/status.go
  pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/hubble/api/const.go
  vendor/github.com/cilium/cilium/pkg/hubble/api/socket.go
  vendor/modules.txt
Labels: ⌨️ area/cli

#225 fix: add skipped quote in hubble-all-minikube.yaml
  tutorials/deploy-hubble-servicemap/hubble-all-minikube.yaml
Labels: 🐛 kind/bug, 🖥 area/ui

#226 update Go version to v1.14.2
  .github/workflows/unittests.yml
  Dockerfile
Labels: area/misc, release-note/misc

#239 Bring back HUBBLE_DEFAULT_SOCKET_PATH env var
  cmd/observe/observe.go
  cmd/status/status.go
  pkg/defaults/defaults.go
Labels: ⌨️ area/cli

#248 cmd: add hidden 'peer' command
  cmd/peer/peer.go
  cmd/root.go
  vendor/github.com/cilium/cilium/api/v1/peer/peer.pb.go
  vendor/github.com/cilium/cilium/api/v1/peer/peer.pb.json.go
  vendor/github.com/cilium/cilium/api/v1/peer/peer.pb.validate.go
  vendor/github.com/cilium/cilium/api/v1/peer/peer.proto
  vendor/modules.txt
Labels: release-note/misc, ⌨️ area/cli, 🌟 kind/feature
