Repository cilium/hubble, pull requests merged in 2020-03, with the labels that each got.

#173 server: Log server configuration parameters
  cmd/serve/serve.go
  pkg/server/local_observer.go
Labels: 📈 kind/enhancement

#175 make: add bench target to run benchmarks
  Makefile
Labels: area/misc, 📈 kind/enhancement

#169 add git branch and hash information to version command
  Makefile
  cmd/version/version.go
  pkg/version.go
Labels: ⌨️ area/cli, 📈 kind/enhancement

#179 api/endpoint: stop marking endpoints as deleted, just remove them
  pkg/api/v1/endpoint.go
  pkg/api/v1/endpoint_test.go
  pkg/api/v1/types.go
  pkg/cilium/endpoint.go
  pkg/cilium/endpoint_test.go
  pkg/parser/endpoint/endpoint.go
  pkg/parser/endpoint/endpoint_test.go
  pkg/testutils/fake.go
Labels: 🧹 kind/cleanup

#185 cmd/serve: remove duration option
  cmd/serve/serve.go
Labels: :no_good_man: upgrade-impact, ⌨️ area/cli

#186 api/endpoint: remove Created field from endpoint struct
  pkg/api/v1/endpoint.go
  pkg/api/v1/endpoint_test.go
  pkg/api/v1/types.go
  pkg/cilium/endpoint_test.go
  pkg/parser/endpoint/endpoint.go
  pkg/parser/endpoint/endpoint_test.go
Labels: 🧹 kind/cleanup

#187 proto: Remove ProtocolMessage
  api/v1/observer/observer.pb.go
  api/v1/observer/observer.pb.json.go
  api/v1/observer/observer.pb.validate.go
  api/v1/observer/observer.proto
  cmd/observe/observe.go
Labels: 👀 pending-review, 🧹 kind/cleanup

#194 fqdn: Refactor FqdnCache interface
  pkg/cilium/dns.go
  pkg/cilium/dns_test.go
  pkg/parser/seven/parser_test.go
  pkg/parser/threefour/parser_test.go
  pkg/testutils/fake.go
Labels: area/misc, 👀 pending-review, 🧹 kind/cleanup

#196 cmd: make SetupListeners public, allow specifying socket group
  cmd/serve/serve.go
  pkg/api/socket.go
  pkg/api/socket_test.go
Labels: area/misc, release-note/misc, ⌨️ area/cli, 📈 kind/enhancement

#193 server: Introduce hooks for extending server functionality
  pkg/server/local_observer.go
  pkg/server/local_observer_test.go
  pkg/server/serveroption/option.go
Labels: 👀 pending-review, 📈 kind/enhancement

#199 api: fix potential panic in endpoint's EqualsByID
  pkg/api/v1/endpoint.go
  pkg/api/v1/endpoint_test.go
Labels: area/misc, release-note/bug, 🐛 kind/bug

#208 cmd/serve: refactor, introduce Server struct and options
  cmd/serve/option.go
  cmd/serve/serve.go
  cmd/serve/server.go
Labels: ⌨️ area/cli, 🧹 kind/cleanup
