Repository cilium/hubble, pull requests merged in 2020-08, with the labels that each got.

#336 update Go version to v1.14.7
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: needs-backport/0.5, needs-backport/0.6, ready-to-merge, release-note/misc

#338 v0.6: backports 2020-08-10
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: backport/0.6, 🧰 kind/backport

#337 v0.5: backports 2020-08-10
  .github/workflows/unittests.yml
  Dockerfile
Labels: backport/0.5, 🧰 kind/backport

#340 tutorials: Fix README.md
  tutorials/README.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation

#341 Clarify wording in README
  README.md
Labels: ready-to-merge, release-note/misc

#342 printer: avoid duplicate import
  pkg/printer/printer.go
Labels: ready-to-merge, release-note/misc

#345 cmd/status: do not report flows ratio when max flows is zero
  cmd/status/status.go
Labels: needs-backport/0.6, ready-to-merge, release-note/bug, ⌨️ area/cli

#346 cmd/status: report current/max flows on the same line
  cmd/status/status.go
Labels: release-note/minor, ⌨️ area/cli

#343 Update Go to v1.15, drop support for darwin/386, add support for linux/[arm,arm64]
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/minor

#347 printer: use fmt.Fprintln instead of fmt.Fprintf
  pkg/printer/printer.go
Labels: ready-to-merge, release-note/misc, 🧹 kind/cleanup

#348 v0.6: cmd/status: do not report flows ratio when max flows is zero
  cmd/status/status.go
Labels: backport/0.6, 🧰 kind/backport

#351 README: Update links
  README.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation

#355 Dockerfile: Remove ENTRYPOINT
  Dockerfile
Labels: needs-backport/0.6, release-note/minor
