Repository cilium/hubble, pull requests merged in 2020-05, with the labels that each got.

#258 update Go version to v1.14.3
  .github/workflows/unittests.yml
  Dockerfile
Labels: area/misc, release-note/misc

#261 printer: Fall back on ethernet MAC addresses
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ⌨️ area/cli

#262 printer: Fall back on ethernet MAC addresses
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ⌨️ area/cli

#268 make: optimize binary size by omitting symbol table and debug info
  Makefile
Labels: 📈 kind/enhancement
