Repository cilium/hubble, pull requests merged in 2020-11, with the labels that each got.

#414 docs: Point to stable documentation
  Documentation/README.md
  README.md
  install/kubernetes/README.md
Labels: ready-to-merge, release-note/misc

#420 cmd/config: add shell completion support for keys for get|set|reset
  cmd/config/get.go
  cmd/config/reset.go
  cmd/config/set.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli, 🌟 kind/feature

#416 Update Go to 1.15.4
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#417 v0.6: update Go to 1.14.11
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#418 v0.5: update Go to 1.14.11
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc

#419 v0.7: update Go version to 1.15.4
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#421 cmd/observe: add shell completion support for various flags
  cmd/observe/observe.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli, 🌟 kind/feature

#423 Update Go to 1.15.5
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: area/misc, ready-to-merge, release-note/misc

#424 v0.7: Update Go to 1.15.5
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: backport/0.7, release-note/misc, 🧰 kind/backport

#425 v0.6: Update Go to 1.14.12
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: backport/0.6, release-note/misc, 🧰 kind/backport

#426 v0.5: Update Go to 1.14.12
  .github/workflows/unittests.yml
  Dockerfile
Labels: backport/0.5, release-note/misc, 🧰 kind/backport

#432 make: set missing IMAGE_TAG variable
  Makefile
Labels: needs-backport/0.5, needs-backport/0.6, needs-backport/0.7, ready-to-merge, release-note/misc, 🐛 kind/bug

#435 v0.7: make: set missing IMAGE_TAG variable
  Makefile
Labels: backport/0.7, ready-to-merge, release-note/misc, 🧰 kind/backport

#436 v0.6: make: set missing IMAGE_TAG variable
  Makefile
Labels: backport/0.6, release-note/misc, 🧰 kind/backport

#437 vendor: bump google.golang.org to v1.33.2
  go.mod
  go.sum
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/credentials/spiffe.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc
