Repository cilium/hubble, pull requests merged in 2020-01, with the labels that each got.

#53 refactor: Move FakeIdentityGetter to testutils
  pkg/parser/threefour/parser_test.go
  pkg/testutils/fake.go
Labels: area/misc, kind/cleanup, pending-review

#54 make: fix clean target
  Makefile
Labels: area/misc, kind/bug, pending-review

#57 parser: replace empty getter implementations by noop getters
  pkg/parser/seven/parser_test.go
  pkg/parser/threefour/parser_test.go
Labels: kind/cleanup

#61 refactor: Consolidate format and printer packages
  cmd/observe/observe.go
  cmd/serve/serve.go
  pkg/format/format.go
  pkg/format/format_test.go
  pkg/printer/options.go
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: pending-review

#64 serve: Add a "local" server
  cmd/serve/serve.go
  pkg/server/dns_test.go
  pkg/server/endpoint_test.go
  pkg/server/local_observer.go
  pkg/server/local_observer_test.go
  pkg/server/observer.go
Labels: kind/feature, pending-review
