Repository cilium/hubble, pull requests merged in 2020-02, with the labels that each got.

#69 server: Refactor LocalObserverServer and ObserverServer
  cmd/serve/serve.go
  pkg/server/dns_test.go
  pkg/server/endpoint_test.go
  pkg/server/ipcache_test.go
  pkg/server/local_observer.go
  pkg/server/observer.go
  pkg/server/observer_test.go
  pkg/server/service_test.go
Labels: kind/cleanup, pending-review, release-note/misc

#77 container|ipcache: remove unused struct fields
  pkg/container/ring_reader.go
  pkg/ipcache/ipcache_test.go
Labels: kind/cleanup

#84 refactor: Move Cilium state caches to cilium package
  cmd/serve/serve.go
  pkg/cilium/client/client.go
  pkg/cilium/dns.go
  pkg/cilium/dns_test.go
  pkg/cilium/endpoint.go
  pkg/cilium/endpoint_test.go
  pkg/cilium/ipcache.go
  pkg/cilium/ipcache_test.go
  pkg/cilium/service.go
  pkg/cilium/service_test.go
  pkg/cilium/state.go
  pkg/server/observer.go
  pkg/server/observer_test.go
Labels: area/misc, kind/cleanup, pending-review, release-note/misc

#85 endpoint: Add a function to lookup by pod name
  pkg/api/v1/endpoint.go
  pkg/api/v1/endpoint_test.go
  pkg/testutils/fake.go
Labels: area/misc, kind/enhancement, pending-review, release-note/misc

#103 cmd/observe: fix 2 context leaks
  cmd/observe/observe.go
Labels: kind/cleanup

#109 serve: Remove printf
  cmd/serve/serve.go
Labels: area/misc, kind/cleanup, pending-review, release-note/misc

#112 api: Fix broken trailing space in make v4.3
  api/v1/Makefile
Labels: pending-review

#119 service: Remove unused GetServiceByID()
  pkg/parser/getters/getters.go
  pkg/servicecache/service_cache.go
  pkg/servicecache/service_cache_test.go
  pkg/testutils/fake.go
Labels: area/misc, pending-review

#123 socket: Make the unix domain socket group configurable
  install/kubernetes/hubble/templates/daemonset.yaml
  install/kubernetes/hubble/values.yaml
  pkg/api/const.go
  pkg/api/socket.go
  pkg/api/socket_test.go
Labels: pending-review

#130 doc: set minimum recommended cilium version to v1.7.0
  Documentation/installation.md
Labels: area/documentation, release-note/misc

#129 vendor: update cilium to v1.7.0
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/pkg/client/endpoint.go
  vendor/github.com/cilium/cilium/pkg/defaults/node.go
  vendor/github.com/cilium/cilium/pkg/endpoint/id/allocator.go
  vendor/github.com/cilium/cilium/pkg/identity/config.go
  vendor/github.com/cilium/cilium/pkg/metrics/status.go
  vendor/github.com/cilium/cilium/pkg/monitor/agent/listener/listener.go
  vendor/github.com/cilium/cilium/pkg/option/config.go
  vendor/modules.txt
Labels: area/misc, release-note/misc

#133 printer: Pass right parameters to Hostname() function
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: area/misc, kind/bug, pending-review

#132 cmd/observe: deprecate --compact, --dict, --json flags, add --output
  cmd/observe/observe.go
  pkg/printer/options.go
Labels: area/cli, kind/enhancement

#154 container/ring: replace references to 'flow' by 'event'
  pkg/container/ring.go
  pkg/container/ring_test.go
Labels: kind/cleanup

#163 server: Make event queue size configurable
  cmd/serve/serve.go
  pkg/server/local_observer.go
  pkg/server/local_observer_test.go
  pkg/server/observer.go
  pkg/server/observer_test.go
Labels: 📈 kind/enhancement
