Repository cilium/hubble, pull requests merged in 2020-12, with the labels that each got.

#441 vendor: Bump gopkg.in/yaml.v2 to v2.4.0
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/.travis.yml
  vendor/gopkg.in/yaml.v2/apic.go
  vendor/gopkg.in/yaml.v2/go.mod
  vendor/gopkg.in/yaml.v2/yaml.go
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc

#444 completion: remove the copyright header
  cmd/completion/completion.go
Labels: :low_brightness: priority/low, area/misc, needs-backport/0.7, ready-to-merge, release-note/misc, 📈 kind/enhancement

#446 Update Go to 1.15.6
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: area/misc, ready-to-merge, release-note/misc

#447 v0.7: Update Go to 1.15.6
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: area/misc, ready-to-merge, release-note/misc

#448 v0.6: Update Go to 1.14.13
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: area/misc, release-note/misc

#449 v0.5: Update Go to 1.14.13
  .github/workflows/unittests.yml
  Dockerfile
Labels: area/misc, release-note/misc

#454 Agent event follow-up fixes for #442
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ready-to-merge, release-note/misc, 🧹 kind/cleanup

#452 Switch protobuf module to google.golang.org/protobuf
  cmd/observe/observe.go
  cmd/observe/observe_filter.go
  cmd/reflect/reflect.go
  go.mod
  pkg/printer/printer.go
  pkg/printer/printer_test.go
  vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc, 🧹 kind/cleanup

#457 vendor: bump google.golang.org/grpc to v1.34.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/interceptor.go
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/config_selector.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/serviceconfig/serviceconfig.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/networktype/networktype.go
  vendor/google.golang.org/grpc/internal/transport/proxy.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc

#456 Makefile: Add support for DOCKER_FLAGS environment variable
  Makefile
Labels: release-note/misc, 🤖 area/CI

#461 cmd/observe: support for filtering events based on tcp-flags
  cmd/observe/observe.go
  cmd/observe/observe_filter.go
  cmd/observe/observe_filter_test.go
Labels: ready-to-merge, release-note/major
