Repository cilium/hubble, pull requests merged in 2021-06, with the labels that each got.

#563 .github/workflows: move Go module vendoring check to build checks
  .github/workflows/tests.yml
Labels: ready-to-merge, release-note/misc, 🤖 area/CI

#564 Update Go to 1.16.5
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#565 v0.8: Update Go to 1.16.5
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: backport/0.8, ready-to-merge, release-note/misc

#566 v0.7: Update Go to 1.15.13
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: backport/0.7, ready-to-merge, release-note/misc

#568 readme: clarify that only the latest version is maintained/supported
  README.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation

#569 .github: Rename maintainer's little helper's config file
  .github/maintainers-little-helper.yaml
Labels: area/misc, ready-to-merge, release-note/misc

#573 cmd/observe: do not set `--last` to 20 by default in follow mode
  cmd/observe/observe.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli

#575 ci: fix the go vendoring check
  .github/workflows/tests.yml
Labels: ready-to-merge, release-note/misc, 🤖 area/CI

#576 Add CODEOWNERS
  CODEOWNERS
Labels: release-note/ci, 🤖 area/CI, 🤯 kind/meta

#577 CODEOWNERS: assign GH actions to github-sec team
  CODEOWNERS
Labels: release-note/ci

#578 cmd/observe: move flows specific code to flows*.go files
  cmd/observe/flows.go
  cmd/observe/flows_filter.go
  cmd/observe/flows_filter_test.go
  cmd/observe/flows_test.go
  cmd/observe/observe.go
Labels: area/misc, release-note/misc

#580 CODEOWNERS: assign Go module vendoring to @cilium/vendor
  CODEOWNERS
Labels: release-note/misc
