Repository cilium/hubble, pull requests merged in 2021-01, with the labels that each got.

#464 vendor: bump google.golang.org/grpc to v1.35.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/Makefile
  vendor/google.golang.org/grpc/SECURITY.md
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/internal/grpcutil/target.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/resolver/config_selector.go
  vendor/google.golang.org/grpc/internal/resolver/unix/unix.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_linux.go
  vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: area/misc, ready-to-merge, release-note/misc

#465 cmd/observer: add support for agent event sub-type filters
  cmd/observe/observe_filter.go
  cmd/observe/observe_filter_test.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli

#466 cmd/node: fix completion of output flag
  cmd/node/list.go
Labels: ready-to-merge, release-note/misc, ⌨️ area/cli

#467 Update Go to 1.15.7
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#468 v0.7: Update Go to 1.15.7
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#469 v0.6: Update Go to 1.14.14
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#470 v0.5: Update Go to 1.14.14
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc

#471 cmd: use config key constants instead of hardcoded strings
  cmd/common/config/flags.go
  cmd/common/conn/tls.go
  cmd/common/validate/tls.go
  cmd/config/set.go
  cmd/node/list.go
  cmd/observe/observe.go
  cmd/peer/watch.go
  cmd/reflect/reflect.go
  cmd/status/status.go
Labels: release-note/misc, ⌨️ area/cli

#472 Bump alpine base image to 3.13
  Dockerfile
  Makefile
Labels: release-note/misc
