Repository cilium/hubble, pull requests merged in 2021-02, with the labels that each got.

#475 ci: Add CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: ready-to-merge, release-note/misc, 🤖 area/CI

#474 ci: Add dependabot configuration
  .github/dependabot.yml
Labels: ready-to-merge, release-note/misc, 🤖 area/CI

#478 Update Go to 1.15.8
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#477 ci: fix dependabot kind/enhancement label
  .github/dependabot.yml
Labels: ready-to-merge, release-note/misc, 🐛 kind/bug

#479 v0.7: Update Go to 1.15.8
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#480 v0.6: Update Go to 1.14.15
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#481 v0.5: Update Go to 1.14.15
  .github/workflows/unittests.yml
  Dockerfile
Labels: release-note/misc

#485 ci: do not upload artifacts
  .github/workflows/tests.yml
Labels: ready-to-merge, release-note/misc

#487 update Go to v1.16.0
  .github/workflows/tests.yml
  Dockerfile
  Makefile
  go.sum
Labels: release-note/misc

#488 make: build release binaries for darwin/arm64 (aka Apple silicon)
  Makefile
Labels: ready-to-merge, release-note/minor

#493 Revert "ci: fix dependabot kind/enhancement label"
  .github/dependabot.yml
Labels: release-note/misc, 📈 kind/enhancement

#494 vendor: bump honnef.co/go/tools from v0.1.1 to v0.1.2
  go.mod
  go.sum
  vendor/honnef.co/go/tools/go/ir/exits.go
  vendor/honnef.co/go/tools/lintcmd/version/version.go
  vendor/honnef.co/go/tools/pattern/match.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/honnef.co/go/tools/stylecheck/lint.go
  vendor/modules.txt
Labels: kind/enhancement, ready-to-merge, release-note/misc

#495 doc: #hubble-devel on Slack is now #sig-hubble
  CONTRIBUTING.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation
