Repository cilium/hubble, pull requests merged in 2021-04, with the labels that each got.

#526 Update Go to 1.16.3
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#527 v0.7: Update Go to 1.15.11
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#524 Support reading flows from stdin
  cmd/observe/io_reader_observer.go
  cmd/observe/io_reader_observer_test.go
  cmd/observe/observe.go
  vendor/github.com/cilium/cilium/pkg/defaults/cluster.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/defaults/node.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/event_type.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/filters.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/fqdn.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/http.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/identity.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/ip.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/k8s.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/labels.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/nodename.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/patterns.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/port.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/protocol.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/reply.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/tcp.go
  vendor/github.com/cilium/cilium/pkg/hubble/filters/verdict.go
  vendor/github.com/cilium/cilium/pkg/hubble/k8s/utils.go
  vendor/github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/labels/doc.go
  vendor/github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/labels/labels.go
  vendor/github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/labels/selector.go
  vendor/github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/labels/zz_generated.deepcopy.go
  vendor/github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/labels/zz_generated.deepequal.go
  vendor/github.com/cilium/cilium/pkg/k8s/slim/k8s/apis/selection/operator.go
  vendor/k8s.io/apimachinery/LICENSE
  vendor/k8s.io/apimachinery/pkg/util/errors/doc.go
  vendor/k8s.io/apimachinery/pkg/util/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/util/sets/byte.go
  vendor/k8s.io/apimachinery/pkg/util/sets/doc.go
  vendor/k8s.io/apimachinery/pkg/util/sets/empty.go
  vendor/k8s.io/apimachinery/pkg/util/sets/int.go
  vendor/k8s.io/apimachinery/pkg/util/sets/int32.go
  vendor/k8s.io/apimachinery/pkg/util/sets/int64.go
  vendor/k8s.io/apimachinery/pkg/util/sets/string.go
  vendor/k8s.io/apimachinery/pkg/util/validation/field/errors.go
  vendor/k8s.io/apimachinery/pkg/util/validation/field/path.go
  vendor/k8s.io/apimachinery/pkg/util/validation/validation.go
  vendor/modules.txt
Labels: release-note/minor, ⌨️ area/cli

#529 Add a hidden --flow-export flag
  cmd/serve/serve.go
  go.mod
  go.sum
  pkg/server/unfiltered_exporter.go
  vendor/gopkg.in/natefinch/lumberjack.v2/.gitignore
  vendor/gopkg.in/natefinch/lumberjack.v2/.travis.yml
  vendor/gopkg.in/natefinch/lumberjack.v2/LICENSE
  vendor/gopkg.in/natefinch/lumberjack.v2/README.md
  vendor/gopkg.in/natefinch/lumberjack.v2/chown.go
  vendor/gopkg.in/natefinch/lumberjack.v2/chown_linux.go
  vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go
  vendor/modules.txt
Labels: area/misc, release-note/minor

#532 Bump github.com/cilium/cilium to pull in reworked agent/debug event API
  cmd/observe/io_reader_observer.go
  go.mod
  go.sum
  pkg/printer/printer.go
  pkg/printer/printer_test.go
  vendor/github.com/cilium/cilium/api/v1/observer/observer.pb.go
  vendor/github.com/cilium/cilium/api/v1/observer/observer.pb.json.go
  vendor/github.com/cilium/cilium/api/v1/observer/observer.proto
  vendor/github.com/cilium/cilium/api/v1/observer/observer_grpc.pb.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go
  vendor/github.com/cilium/cilium/pkg/logging/logging.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_aix.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/exec_windows.go
  vendor/golang.org/x/sys/windows/mkerrors.bash
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zerrors_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc

#530 cmd: Add record subcommand
  cmd/record/record.go
  cmd/record/tty_linux.go
  cmd/record/tty_others.go
  cmd/root.go
  go.mod
  vendor/github.com/cilium/cilium/api/v1/recorder/recorder.pb.go
  vendor/github.com/cilium/cilium/api/v1/recorder/recorder.pb.json.go
  vendor/github.com/cilium/cilium/api/v1/recorder/recorder.proto
  vendor/github.com/cilium/cilium/api/v1/recorder/recorder_grpc.pb.go
  vendor/modules.txt
Labels: :basecamp: needs-rebase, ready-to-merge, release-note/minor, ⌨️ area/cli, 🌟 kind/feature

#533 compact: Always print original source on the left
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ready-to-merge, release-note/minor

#534 cmd/observe: don't list agent/debug events and recorder captures in event type filter
  cmd/observe/observe.go
  cmd/observe/observe_test.go
Labels: ready-to-merge, release-note/misc, 🧹 kind/cleanup

#535 change default address to localhost:4245
  cmd/common/config/flags.go
  pkg/defaults/defaults.go
Labels: release-note/minor

#536 RFC: cmd/observe: set default output format to "compact"
  cmd/observe/observe.go
Labels: ready-to-merge, release-note/minor

#539 cmd/observe: use signal.NotifyContext to cancel context on SIGINT
  cmd/observe/observe.go
Labels: ready-to-merge, release-note/misc

#540 Dockerfile: use alpine 3.12
  Dockerfile
Labels: release-note/misc
