Repository cilium/hubble, pull requests merged in 2021-05, with the labels that each got.

#541 cmd: change "node list" command for "list node"
  cmd/list/list.go
  cmd/list/node.go
  cmd/list/node_test.go
  cmd/root.go
Labels: ready-to-merge, release-note/misc

#542 cmd: change 'peers watch' command to 'watch peers'
  cmd/root.go
  cmd/watch/peer.go
  cmd/watch/peer_test.go
  cmd/watch/watch.go
Labels: ready-to-merge, release-note/misc

#546 release: pin skx/github-action-publish-binaries to a specific sha
  .github/workflows/release.yml
Labels: needs-backport/0.8, ready-to-merge, release-note/misc

#547 v0.8: release: pin skx/github-action-publish-binaries to a specific sha
  .github/workflows/release.yml
Labels: backport/0.8, ready-to-merge, release-note/misc, 🧰 kind/backport

#549 v0.8: Update Go to 1.16.4
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#552 vendor: bump grpc to v1.37.1; honnef tools to v0.1.4
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/version.go
  vendor/honnef.co/go/tools/analysis/report/report.go
  vendor/honnef.co/go/tools/go/ir/dom.go
  vendor/honnef.co/go/tools/go/ir/lift.go
  vendor/honnef.co/go/tools/lintcmd/version/version.go
  vendor/honnef.co/go/tools/simple/lint.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/modules.txt
Labels: needs-backport/0.8, ready-to-merge, release-note/misc

#553 v0.8: vendor: bump grpc to v1.37.1; honnef tools to v0.1.4
  go.mod
  go.sum
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/version.go
  vendor/honnef.co/go/tools/analysis/report/report.go
  vendor/honnef.co/go/tools/go/ir/dom.go
  vendor/honnef.co/go/tools/go/ir/lift.go
  vendor/honnef.co/go/tools/lintcmd/version/version.go
  vendor/honnef.co/go/tools/simple/lint.go
  vendor/honnef.co/go/tools/staticcheck/lint.go
  vendor/modules.txt
Labels: ready-to-merge, release-note/misc, 🧰 kind/backport

#555 .github: Cancel outdated PR and push workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/tests.yml
Labels: ready-to-merge, release-note/ci, 🤖 area/CI

#560 Makefile: Introduce GO_BUILD variable
  Makefile
Labels: ready-to-merge, release-note/misc

#562 pkg/printer: disable color output in tests
  pkg/printer/printer_test.go
Labels: ready-to-merge, release-note/misc
