Repository cilium/hubble, pull requests merged in 2021-08, with the labels that each got.

#603 cmd/observe: remove depreacted formatting flags (json, compact, dict)
  cmd/observe/flows.go
  cmd/observe/observe.go
Labels: ⌨️ area/cli, release-note/misc, ready-to-merge, needs-backport/0.8

#605 v0.8: Update Go to 1.16.7
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc, 🧰 kind/backport, ready-to-merge, backport/0.8

#604 Update Go to 1.16.7
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#606 v0.8: cmd/observe: remove depreacted formatting flags (json, compact, dict)
  cmd/observe/observe.go
Labels: release-note/misc, 🧰 kind/backport, ready-to-merge, backport/0.8

#611 ci: bump golangci-lint to v1.42.0
  .github/workflows/tests.yml
  Makefile
Labels: release-note/ci

#615 printer: fix dict outout newline
  pkg/printer/printer.go
Labels: ⌨️ area/cli, release-note/bug, ready-to-merge, needs-backport/0.8

#617 v0.8: printer: fix dict outout newline
  pkg/printer/printer.go
Labels: release-note/bug, 🧰 kind/backport, ready-to-merge, backport/0.8
