Repository cilium/hubble, pull requests merged in 2021-07, with the labels that each got.

#585 update Go to v1.16.6, alpine to 3.14
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: needs-backport/0.8, release-note/misc

#587 docker: add note about bogus busybox's nslookup implementation
  Dockerfile
Labels: needs-backport/0.8, release-note/misc

#589 git commands in the Makefile return the empty string if they fail.
  Makefile
Labels: needs-backport/0.8, release-note/misc

#593 Fix broken link
  README.md
Labels: release-note/misc

#598 Log a debug message when reading from stdin
  cmd/observe/flows.go
Labels: ready-to-merge, release-note/misc
