Repository cilium/hubble, pull requests merged in 2021-09, with the labels that each got.

#618 build release binaries for Windows ARM64
  Makefile
Labels: release-note/minor

#619 [v0.8] go.mod, vendor: bump cilium to v1.10.4
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/modules.txt
Labels: release-note/misc

#624 RELEASE.md: document Homebrew formular update as optional step
  RELEASE.md
Labels: release-note/misc, ready-to-merge

#625 ci: bump Go to 1.17 for golangci-lint
  .golangci.yml
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/misc

#627 github: Add "Image Release Build" workflow
  .github/workflows/build-images-release.yaml
Labels: release-note/misc
