Repository cilium/hubble, pull requests merged in 2021-03, with the labels that each got.

#498 vendor: bump google.golang.org/grpc to v1.36.0
  go.mod
  go.sum
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: kind/enhancement, ready-to-merge, release-note/misc

#500 Fix brokenlink on README.md
  README.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation

#496 cmd/node: Refactor & Test output methods
  cmd/node/list.go
  cmd/node/list_test.go
Labels: ready-to-merge, release-note/misc, 🤖 area/CI

#499 cmd/peer: Refactor and test processing of response
  cmd/peer/watch.go
  cmd/peer/watch_test.go
Labels: ready-to-merge, release-note/misc, 🤖 area/CI

#504 vendor: bump github.com/google/go-cmp from 0.5.4 to 0.5.5
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/modules.txt
Labels: kind/enhancement, ready-to-merge, release-note/misc

#502 cmd/observe: print filters in debug mode
  cmd/observe/observe.go
  cmd/observe/observe_filter.go
Labels: kind/enhancement, ready-to-merge, release-note/misc

#506 cmd/observe: mark deprecated output flags as deprecated
  cmd/observe/observe.go
Labels: ready-to-merge, release-note/minor, ⌨️ area/cli

#508 v0.7: Update Go to 1.15.9
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#510 Update Go to 1.16.2
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#511 v0.7: Update Go to 1.15.10
  .github/workflows/unittests.yml
  Dockerfile
  Makefile
Labels: ready-to-merge, release-note/misc

#513 vendor: bump honnef.co/go/tools from v0.1.2 to v0.1.3
  go.mod
  go.sum
  vendor/honnef.co/go/tools/lintcmd/version/version.go
  vendor/honnef.co/go/tools/unused/typemap/identical.go
  vendor/honnef.co/go/tools/unused/typemap/map.go
  vendor/honnef.co/go/tools/unused/unused.go
  vendor/modules.txt
Labels: kind/enhancement, ready-to-merge, release-note/misc

#517 vendor: Fix grpc version (1.33 doesn't exist)
  go.mod
  go.sum
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/internal/credentials/spiffe.go
  vendor/google.golang.org/grpc/reflection/grpc_reflection_v1alpha/reflection.pb.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: release-note/misc

#520 Update RELEASE.md with `-dev` change
  RELEASE.md
Labels: ready-to-merge, release-note/misc, 📄 area/documentation
