Repository cilium/hubble, pull requests merged in 2022-07, with the labels that each got.

#759 compact: Add traffic direction to policy verdict events
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: release-note/minor, ready-to-merge

#760 Update Go to 1.18.4
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#761 v0.9: Update Go to 1.17.12, alpine to 3.16
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc, 🧰 kind/backport, backport/0.9

#767 CODEOWNERS: update teams following removal of non-sig teams
  CODEOWNERS
Labels: release-note/misc, ready-to-merge
