Repository cilium/hubble, pull requests merged in 2022-08, with the labels that each got.

#769 Use command path when registering flagsets
  cmd/common/template/usage.go
  cmd/common/template/usage_test.go
  cmd/list/list.go
  cmd/list/node.go
  cmd/observe/agent_events.go
  cmd/observe/debug_events.go
  cmd/observe/flows.go
  cmd/record/record.go
  cmd/reflect/reflect.go
  cmd/root.go
  cmd/status/status.go
  cmd/watch/watch.go
Labels: release-note/misc, ready-to-merge

#772 Update Go to 1.18.5
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#774 v0.10: Update Go to 1.18.5
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc, 🧰 kind/backport, backport/0.10

#781 v0.10: printer: fix argument order in strings.HasPrefix call
  pkg/printer/printer.go
Labels: release-note/misc, 🧰 kind/backport, backport/0.10
