Repository cilium/hubble, pull requests merged in 2022-02, with the labels that each got.

#681 Update Go to 1.17.7
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#682 v0.9: Update Go to 1.17.7
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc, 🧰 kind/backport, backport/0.9

#684 cmd/config: ensure that the configuration directory exist
  cmd/config/set.go
Labels: release-note/bug
