Repository cilium/hubble, pull requests merged in 2022-06, with the labels that each got.

#732 named reserved identites support for `--{,from-,to-}identity`
  cmd/observe/flows.go
  cmd/observe/flows_filter.go
  cmd/observe/flows_filter_test.go
  cmd/observe/identity.go
Labels: kind/enhancement, ⌨️ area/cli, release-note/misc, ready-to-merge

#730 improve cli help text for service filtering
  cmd/observe/flows.go
Labels: 📄 area/documentation, kind/enhancement, ⌨️ area/cli, release-note/misc

#731 docs: update the cli doc with cidr range source/destination ip filter
  cmd/observe/flows.go
Labels: ⌨️ area/cli, release-note/misc, ready-to-merge

#733 docs: Document pod/service filter prefix behavior
  cmd/observe/flows.go
Labels: 📄 area/documentation, ⌨️ area/cli, release-note/misc

#745 cmd/observe: improve policy verdict output in compact mode
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ⌨️ area/cli, release-note/minor

#748 vendor: Bump Cilium to v1.12 branch
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/api/v1/client/policy/get_fqdn_cache_id_parameters.go
  vendor/github.com/cilium/cilium/api/v1/client/policy/get_fqdn_cache_parameters.go
  vendor/github.com/cilium/cilium/api/v1/client/policy/policy_client.go
  vendor/github.com/cilium/cilium/api/v1/models/backend_address.go
  vendor/github.com/cilium/cilium/api/v1/models/node_element.go
  vendor/github.com/cilium/cilium/api/v1/models/zz_generated.deepcopy.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/defaults/node.go
  vendor/github.com/cilium/cilium/pkg/identity/identity.go
  vendor/github.com/cilium/cilium/pkg/identity/numericidentity.go
  vendor/github.com/cilium/cilium/pkg/identity/reserved.go
  vendor/github.com/cilium/cilium/pkg/ipam/option/option.go
  vendor/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/const.go
  vendor/github.com/cilium/cilium/pkg/labels/labels.go
  vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go
  vendor/github.com/cilium/cilium/pkg/metrics/metrics.go
  vendor/github.com/cilium/cilium/pkg/metrics/middleware.go
  vendor/github.com/cilium/cilium/pkg/option/config.go
  vendor/github.com/go-openapi/validate/default_validator.go
  vendor/github.com/go-openapi/validate/example_validator.go
  vendor/github.com/go-openapi/validate/helpers.go
  vendor/github.com/go-openapi/validate/spec.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/collectors.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/collectors/go_collector_latest.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_go116.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector_latest.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/go_runtime_metrics.go
  vendor/gopkg.in/ini.v1/.golangci.yml
  vendor/gopkg.in/ini.v1/README.md
  vendor/gopkg.in/ini.v1/codecov.yml
  vendor/gopkg.in/ini.v1/error.go
  vendor/gopkg.in/ini.v1/file.go
  vendor/gopkg.in/ini.v1/parser.go
  vendor/modules.txt
Labels: release-note/misc, ready-to-merge

#753 CHANGELOG.md: fix PR ref in the v0.10.0 release note
  CHANGELOG.md
Labels: 📄 area/documentation, 🧹 kind/cleanup, :low_brightness: priority/low, release-note/misc, needs-backport/0.10

#754 [v0.10] CHANGELOG.md: fix PR ref in the v0.10.0 release note
  CHANGELOG.md
Labels: 📄 area/documentation, release-note/misc, 🧰 kind/backport, backport/0.10
