Repository cilium/hubble, pull requests merged in 2022-05, with the labels that each got.

#716 v0.9: Update Go to 1.17.10
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: release-note/misc

#717 printer: Display security identity in compact output
  pkg/printer/color.go
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: ⌨️ area/cli, release-note/major

#722 ci: use hashes for all GitHub Action modules
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: 🤖 area/CI, release-note/misc

#723 Dockerfile: fix golang image name to v1.18.2
  Dockerfile
Labels: release-note/misc, ready-to-merge

#718 Refactor usage template to determine --help flags using a registration pattern
  cmd/common/template/usage.go
  cmd/common/template/usage_test.go
  cmd/list/list.go
  cmd/list/node.go
  cmd/observe/agent_events.go
  cmd/observe/debug_events.go
  cmd/observe/flows.go
  cmd/record/record.go
  cmd/reflect/reflect.go
  cmd/root.go
  cmd/status/status.go
  cmd/watch/watch.go
Labels: release-note/misc, ready-to-merge
