Repository cilium/hubble, pull requests merged in 2023-09, with the labels that each got.

#1200 doc: update doc readme and remove broken links
  Documentation/README.md
Labels: release-note/misc, ready-to-merge

#1202 Fix raw-filter flags by binding flags to viper only if command is run
  cmd/cli_test.go
  cmd/observe/flows.go
Labels: kind/enhancement, ⌨️ area/cli, release-note/bug

#1203 Add filter flag documentation and examples to help message
  cmd/observe/flows.go
Labels: 📄 area/documentation, kind/enhancement, release-note/misc, ready-to-merge

#1229 doc: add server flag documentation to watch peers
  cmd/watch/peer.go
Labels: 📄 area/documentation, kind/enhancement, release-note/misc, ready-to-merge
