Repository cilium/hubble, pull requests merged in 2023-06, with the labels that each got.

#1064 ci: enable new linters
  .golangci.yml
  cmd/cli_test.go
Labels: 🤖 area/CI, release-note/misc, ready-to-merge

#1070 make: add renovate anchor to the release target golang image
  Makefile
Labels: kind/enhancement, 🤖 area/CI, release-note/misc

#1072 make: add renovate anchor to the release target golang image
  Makefile
Labels: kind/enhancement, 🤖 area/CI, release-note/misc

#1076 v0.11: vendor: update Cilium from v1.13.2 to v1.13.3
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/flow/README.md
  vendor/github.com/cilium/cilium/api/v1/flow/flow.pb.go
  vendor/github.com/cilium/cilium/api/v1/flow/flow.proto
  vendor/github.com/cilium/cilium/api/v1/observer/observer.pb.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/ip/cidr.go
  vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go
  vendor/github.com/cilium/cilium/pkg/monitor/api/drop.go
  vendor/modules.txt
Labels: release-note/misc

#1085 Add golang to matchPackageNames for go deps groups
  .github/renovate.json5
Labels: kind/enhancement, 🤖 area/CI, release-note/ci

#1097 build: Bump golang image to alpine v3.18
  Dockerfile
  Makefile
Labels: kind/enhancement, area/misc, release-note/misc, ready-to-merge

#1086 Add hubble list namespaces command
  cmd/list/list.go
  cmd/list/namespace_test.go
  cmd/list/namespaces.go
  cmd/list/node.go
  cmd/list/node_test.go
Labels: ⌨️ area/cli, 🌟 kind/feature, release-note/major
