Repository cilium/hubble, pull requests merged in 2023-02, with the labels that each got.

#889 make: use `command -v` instead of `which` for better portability
  Makefile
Labels: release-note/misc, ready-to-merge

#875 Hubble observe flows
  cmd/cli_test.go
  cmd/observe/agent_events.go
  cmd/observe/debug_events.go
  cmd/observe/flows.go
  cmd/observe/flows_filter_test.go
  cmd/observe/observe.go
  cmd/observe_help.txt
Labels: release-note/minor

#906 Update Go to v1.19.6
  .github/workflows/tests.yml
  Makefile
Labels: release-note/misc

#909 README: Fix broken links
  README.md
Labels: release-note/misc
