Repository cilium/hubble, pull requests merged in 2023-08, with the labels that each got.

#1169 v0.12: ci: build image for arm64
  .github/workflows/build-images-release.yaml
Labels: kind/enhancement, 🤖 area/CI, release-note/misc, 🧰 kind/backport, ready-to-merge, backport/0.12

#1175 Renovate: Attempt to update Makefile golang with other Go deps
  .github/renovate.json5
Labels: release-note/ci, ready-to-merge

#1183 ci: run slowg analyzer
  .github/workflows/tests.yml
Labels: 🤖 area/CI, release-note/ci
