Repository cilium/hubble, pull requests merged in 2023-10, with the labels that each got.

#1245 Revert "chore(deps): update golang to v1.21.1"
  .github/workflows/integration-tests.yaml
  .github/workflows/tests.yml
  Dockerfile
  Makefile
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/misc

#1244 renovate: Use allowedVersions to limit updates to stable branches
  .github/renovate.json5
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/misc, ready-to-merge

#1252 v0.12: vendor: update golang.org/x/net to v0.17.0 [security]
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/text/unicode/norm/trie.go
  vendor/modules.txt
Labels: release-note/misc

#1269 vendor: Fix missing file in vendor
  vendor/google.golang.org/grpc/resolver/manual/manual.go
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/misc, ready-to-merge, dependencies

#1272 Display server provided flows rate
  pkg/printer/printer.go
  pkg/printer/printer_test.go
Labels: release-note/minor, ready-to-merge

#1278 renovate: Configure automerge only from trusted packages
  .github/renovate.json5
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/ci
