Repository cilium/hubble, pull requests merged in 2023-03, with the labels that each got.

#913 Improve help message for --last option
  cmd/observe/observe.go
  cmd/observe_help.txt
Labels: 📄 area/documentation, release-note/misc

#929 cmd/observe: improve help message for --first and --all options
  cmd/observe/observe.go
  cmd/observe_help.txt
Labels: 📄 area/documentation, release-note/misc, ready-to-merge

#930 [v0.11] Update Golang to v1.19.7
  .github/workflows/tests.yml
  Makefile
Labels: release-note/misc, ready-to-merge

#956 cmd/observe: improve help message for date formats of --since/--until
  cmd/observe/observe.go
  cmd/observe_help.txt
Labels: 📄 area/documentation, kind/enhancement, release-note/misc, ready-to-merge

#940 Newest stable release is Hubble v0.11.3
  CHANGELOG.md
  README.md
  stable.txt
Labels: release-note/misc, ready-to-merge

#951 Replace stdin detection with --flows-file flag which supports reading flows from a file or stdin
  cmd/common/config/flags.go
  cmd/observe/flows.go
  cmd/observe/observe.go
  cmd/observe_help.txt
Labels: release-note/major, ready-to-merge, breaking-change
