Repository cilium/hubble, pull requests merged in 2023-04, with the labels that each got.

#975 v0.11/vendor: bump cilium to v1.13.1
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/client/daemon/daemon_client.go
  vendor/github.com/cilium/cilium/api/v1/client/daemon/get_cgroup_dump_metadata_parameters.go
  vendor/github.com/cilium/cilium/api/v1/client/daemon/get_cgroup_dump_metadata_responses.go
  vendor/github.com/cilium/cilium/api/v1/client/daemon/get_node_ids_parameters.go
  vendor/github.com/cilium/cilium/api/v1/client/daemon/get_node_ids_responses.go
  vendor/github.com/cilium/cilium/api/v1/models/cgroup_container_metadata.go
  vendor/github.com/cilium/cilium/api/v1/models/cgroup_dump_metadata.go
  vendor/github.com/cilium/cilium/api/v1/models/cgroup_pod_metadata.go
  vendor/github.com/cilium/cilium/api/v1/models/node_id.go
  vendor/github.com/cilium/cilium/pkg/health/client/client.go
  vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go
  vendor/github.com/cilium/cilium/pkg/metrics/metrics.go
  vendor/github.com/cilium/cilium/pkg/option/config.go
  vendor/golang.org/x/net/http2/flow.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/hpack/hpack.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/trace/histogram.go
  vendor/golang.org/x/sys/unix/gccgo_c.c
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/syscall_freebsd_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_unix.go
  vendor/golang.org/x/sys/unix/timestruct.go
  vendor/golang.org/x/sys/unix/xattr_bsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/modules.txt
Labels: release-note/misc, ready-to-merge

#995 Log when connection is successful
  cmd/observe/flows.go
Labels: ⌨️ area/cli, release-note/misc

#962 observe: warn on unknown field while JSON decoding
  cmd/observe/io_reader_observer.go
  cmd/observe/io_reader_observer_test.go
Labels: kind/enhancement, ⌨️ area/cli, release-note/misc, ready-to-merge

#1001 Update things after 0.11.4 release
  CHANGELOG.md
  README.md
  stable.txt
Labels: 📄 area/documentation, 🧹 kind/cleanup, release-note/misc

#996 Do not fail if unable to provide client certificate when requested
  cmd/common/conn/tls.go
Labels: kind/enhancement, ⌨️ area/cli, release-note/misc, ready-to-merge

#1002 Add support for supplying basic authentication credentials
  .golangci.yml
  cmd/common/config/flags.go
  cmd/common/conn/auth.go
  cmd/common/validate/auth.go
  cmd/observe_help.txt
  cmd/root.go
Labels: 🌟 kind/feature, release-note/major, ready-to-merge
