Repository cilium/hubble, pull requests merged in 2023-07, with the labels that each got.

#1109 fix workload and identity filters
  cmd/observe/flows_filter.go
  cmd/observe/flows_filter_test.go
Labels: 🐛 kind/bug, ⌨️ area/cli, priority/release-blocker, release-note/bug, needs-backport/0.11

#1113 [v0.11] fix workload and identity filters
  cmd/observe/flows_filter.go
  cmd/observe/flows_filter_test.go
Labels: ⌨️ area/cli, release-note/bug, 🧰 kind/backport

#1120 vendor: bump Cilium to v1.14.0-rc.0
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/models/ip_v4_big_tcp.go
  vendor/github.com/cilium/cilium/api/v1/models/ip_v6_big_tcp.go
  vendor/github.com/cilium/cilium/api/v1/models/kube_proxy_replacement.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/k8s/apis/cilium.io/register.go
  vendor/github.com/cilium/cilium/pkg/logging/logfields/logfields.go
  vendor/github.com/cilium/cilium/pkg/option/config.go
  vendor/github.com/go-openapi/errors/api.go
  vendor/github.com/go-openapi/swag/util.go
  vendor/github.com/vishvananda/netlink/handle_unspecified.go
  vendor/github.com/vishvananda/netlink/link.go
  vendor/github.com/vishvananda/netlink/link_linux.go
  vendor/github.com/vishvananda/netlink/netlink_unspecified.go
  vendor/github.com/vishvananda/netlink/route_linux.go
  vendor/modules.txt
Labels: release-note/misc

#1124 ci: replace deprecated use of set-output
  .github/workflows/build-images-release.yaml
Labels: 🤖 area/CI, release-note/ci, needs-backport/0.12

#1123 Fix client certificate requests when no client certificate is specified
  cmd/common/conn/tls.go
Labels: 🐛 kind/bug, release-note/bug, needs-backport/0.12

#1147 switch the default git branch from master to main
  .github/renovate.json5
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration-tests.yaml
  .github/workflows/tests.yml
  CODE_OF_CONDUCT.md
  README.md
  RELEASE.md
Labels: 🧹 kind/cleanup, area/misc, release-note/misc, dont-merge/blocked

#1153 Don't set --last if --input-file is specified
  cmd/observe/flows.go
  cmd/observe/flows_test.go
Labels: release-note/misc, ready-to-merge

#1167 renovate: Add client-go to disabled list
  .github/renovate.json5
Labels: release-note/misc
