Repository cilium/hubble, pull requests merged in 2023-01, with the labels that each got.

#836 dependabot config improvements
  .github/dependabot.yml
Labels: kind/enhancement, 🤖 area/CI, release-note/ci, ready-to-merge

#841 update Go to v1.19.5
  .github/workflows/tests.yml
  Makefile
Labels: release-note/misc

#847 dependabot: increase pull request limit and interval
  .github/dependabot.yml
Labels: kind/enhancement, 🤖 area/CI, release-note/ci, ready-to-merge

#848 CHANGELOG: add links for each released version
  CHANGELOG.md
Labels: 📄 area/documentation, release-note/misc

#849 github: Enable dependabot for stable branch
  .github/dependabot.yml
  RELEASE.md
Labels: 🤖 area/CI, release-note/ci, ready-to-merge

#851 Add hubble observe flows
  cmd/observe/agent_events.go
  cmd/observe/debug_events.go
  cmd/observe/flows.go
  cmd/observe/flows_filter_test.go
  cmd/observe/observe.go
Labels: ⌨️ area/cli, 🌟 kind/feature, release-note/minor, ready-to-merge

#865 cmd: Introduce `HUBBLE_COMPAT=legacy-json-output`
  cmd/common/config/compat.go
  cmd/observe/events.go
  cmd/observe/flows.go
  pkg/printer/options.go
  pkg/printer/printer.go
Labels: ⌨️ area/cli, release-note/misc, needs-backport/0.11

#866 [v0.11] cmd: Introduce `HUBBLE_COMPAT=legacy-json-output`
  cmd/common/config/compat.go
  cmd/observe/events.go
  cmd/observe/flows.go
  pkg/printer/options.go
  pkg/printer/printer.go
Labels: release-note/minor, backport/0.11

#869 Revert "Add hubble observe flows"
  cmd/observe/agent_events.go
  cmd/observe/debug_events.go
  cmd/observe/flows.go
  cmd/observe/flows_filter_test.go
  cmd/observe/observe.go
Labels: release-note/misc

#871 vendor: bump github/cilium to v1.13.0-rc5
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/models/kube_proxy_replacement.go
  vendor/github.com/cilium/cilium/api/v1/models/zz_generated.deepcopy.go
  vendor/github.com/cilium/cilium/pkg/client/client.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/metrics/metrics.go
  vendor/github.com/cilium/cilium/pkg/monitor/api/types.go
  vendor/github.com/cilium/cilium/pkg/option/config.go
  vendor/modules.txt
Labels: release-note/misc, needs-backport/0.11

#872 v0.11: vendor: bump github/cilium to v1.13.0-rc5
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/models/kube_proxy_replacement.go
  vendor/github.com/cilium/cilium/api/v1/models/zz_generated.deepcopy.go
  vendor/github.com/cilium/cilium/pkg/client/client.go
  vendor/github.com/cilium/cilium/pkg/defaults/defaults.go
  vendor/github.com/cilium/cilium/pkg/metrics/metrics.go
  vendor/github.com/cilium/cilium/pkg/monitor/api/types.go
  vendor/github.com/cilium/cilium/pkg/option/config.go
  vendor/modules.txt
Labels: release-note/misc, 🧰 kind/backport

#874 Add unit tests for testing hubble args/flags handling
  cmd/cli_test.go
  cmd/observe/agent_events.go
  cmd/observe/debug_events.go
  cmd/observe/events.go
  cmd/observe/flows.go
  cmd/observe/flows_filter_test.go
  cmd/observe/io_reader_observer.go
  cmd/observe/io_reader_observer_test.go
  cmd/observe_help.txt
  cmd/status/status.go
Labels: kind/enhancement, 🤖 area/CI, release-note/ci

#879 dependabot: prefix backport PRs with target-branch version
  .github/dependabot.yml
  RELEASE.md
Labels: kind/enhancement, 🤖 area/CI, release-note/misc

#873 .github: Add integration tests that installs cilium and queries it using Hubble CLI
  .github/cilium-values.yaml
  .github/kind-config.yaml
  .github/workflows/integration-tests.yaml
  .github/workflows/tests.yml
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/ci, ready-to-merge
