Repository cilium/hubble, pull requests merged in 2024-06, with the labels that each got.

#1512 Remove golangci-lint
  .github/workflows/tests.yml
  .golangci.yml
  Makefile
Labels: release-note/ci

#1511 Remove codeql
  .github/workflows/codeql-analysis.yml
Labels: release-note/ci

#1517 [v0.13] Bump golang to v1.21.11
  Dockerfile
  Makefile
  go.mod
Labels: release-note/minor, dependencies

#1519 Update CHANGELOG and README with 0.13.5
  CHANGELOG.md
  README.md
Labels: release-note/misc

#1520 Fix the release issue template
  .github/ISSUE_TEMPLATE/release.md
Labels: release-note/misc
