Repository cilium/hubble, pull requests merged in 2024-07, with the labels that each got.

#1548 build-images-release: Specify pattern when downloading image digests
  .github/workflows/build-images-release.yaml
Labels: release-note/ci

#1553 [v0.13]: Bump golang to v1.21.12
  Dockerfile
  Makefile
  go.mod
Labels: release-note/minor, ready-to-merge, dependencies

#1555 Update CHANGELOG and README for v0.13.6 release
  CHANGELOG.md
  README.md
Labels: release-note/misc, ready-to-merge

#1556 Update stable.txt
  stable.txt
Labels: release-note/misc
