Repository cilium/hubble, pull requests merged in 2024-05, with the labels that each got.

#1477 Prepare for release v1.16.0-pre.2
  CHANGELOG.md
Labels: release-note/misc

#1480 build-images-release: Simplify the tag regex
  .github/workflows/build-images-release.yaml
Labels: release-note/ci, ready-to-merge

#1489 vendor: Bump Cilium to v1.15.4
  go.mod
  go.sum
  vendor/github.com/cilium/cilium/AUTHORS
  vendor/github.com/cilium/cilium/api/v1/flow/README.md
  vendor/github.com/cilium/cilium/api/v1/flow/flow.pb.go
  vendor/github.com/cilium/cilium/api/v1/flow/flow.proto
  vendor/github.com/cilium/cilium/api/v1/observer/observer.pb.go
  vendor/github.com/cilium/cilium/pkg/allocator/allocator.go
  vendor/github.com/cilium/cilium/pkg/api/apierror.go
  vendor/github.com/cilium/cilium/pkg/bpf/bpffs_linux.go
  vendor/github.com/cilium/cilium/pkg/bpf/collection.go
  vendor/github.com/cilium/cilium/pkg/fqdn/restore/restore.go
  vendor/github.com/cilium/cilium/pkg/idpool/idpool.go
  vendor/github.com/cilium/cilium/pkg/kvstore/etcd.go
  vendor/github.com/cilium/cilium/pkg/logging/logging.go
  vendor/github.com/cilium/cilium/pkg/metrics/metrics.go
  vendor/github.com/cilium/cilium/pkg/monitor/api/drop.go
  vendor/github.com/cilium/cilium/pkg/policy/l4.go
  vendor/github.com/cilium/cilium/pkg/policy/visibility.go
  vendor/github.com/cilium/cilium/pkg/rate/api_limiter.go
  vendor/github.com/cilium/cilium/pkg/rate/metrics/metrics.go
  vendor/modules.txt
Labels: release-note/misc, ready-to-merge

#1491 [v0.13] Bump Golang to v1.21.10
  Dockerfile
  Makefile
  go.mod
Labels: release-note/misc, ready-to-merge

#1493 Update changelog, README, and stable.txt to include 0.13.4
  CHANGELOG.md
  README.md
  stable.txt
Labels: release-note/misc, ready-to-merge

#1492 Prepare for v0.13.5 development
  VERSION
Labels: release-note/misc, ready-to-merge
