Repository cilium/hubble, pull requests merged in 2024-01, with the labels that each got.

#1308 Add flags to filter for pods and services in any namespace
  cmd/observe/flows.go
  cmd/observe/flows_filter.go
  cmd/observe/flows_filter_test.go
  cmd/observe_help.txt
Labels: ⌨️ area/cli, release-note/minor, ready-to-merge

#1351 [v0.13] Prepare for v0.13.1
  CHANGELOG.md
  VERSION
Labels: ⏰ kind/release, release-note/misc, ready-to-merge

#1365 Correct release date in README.md
  README.md
Labels: 📄 area/documentation, 🧹 kind/cleanup, release-note/misc
