Repository cilium/hubble, pull requests merged in 2024-03, with the labels that each got.

#1398 [v0.13] Update Go to 1.21.8
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration-tests.yaml
  .github/workflows/tests.yml
  Makefile
  go.mod
Labels: 🤖 area/CI, release-note/misc, ready-to-merge, dependencies

#1397 Switch to using go.mod for version in setup-go GHA
  .github/workflows/codeql-analysis.yml
  .github/workflows/integration-tests.yaml
  .github/workflows/tests.yml
  go.mod
Labels: kind/enhancement, 🤖 area/CI, release-note/misc, dependencies

#1408 Prepare for v0.13.2
  VERSION
Labels: 🧹 kind/cleanup, area/misc, release-note/misc

#1412 Dockerfile: Update to Go 1.21.8 and Alpine 3.19.1
  Dockerfile
Labels: kind/enhancement, 🤖 area/CI, release-note/minor

#1414 Prepare for 0.13.3
  VERSION
Labels: 🧹 kind/cleanup, area/misc, release-note/misc

#1416 .github: Update renovate for v0.13 branches
  .github/renovate.json5
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/ci

#1417 github: Run Docker build on all PRs
  .github/workflows/build-images-release.yaml
Labels: 🤖 area/CI, release-note/ci, ready-to-merge

#1411 Makefile: Add renovate-local target
  Makefile
Labels: 🧹 kind/cleanup, 🤖 area/CI, release-note/ci

#1424 README: Fix CLI example
  README.md
Labels: release-note/misc
